/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// EmailMessageInfo struct for EmailMessageInfo
type EmailMessageInfo struct {
	MessageCount *int32              `json:"messageCount,omitempty"`
	MessageId    *string             `json:"messageId,omitempty"`
	Status       *EmailMessageStatus `json:"status,omitempty"`
	To           *string             `json:"to,omitempty"`
}

// NewEmailMessageInfo instantiates a new EmailMessageInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailMessageInfo() *EmailMessageInfo {
	this := EmailMessageInfo{}
	return &this
}

// NewEmailMessageInfoWithDefaults instantiates a new EmailMessageInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailMessageInfoWithDefaults() *EmailMessageInfo {
	this := EmailMessageInfo{}
	return &this
}

// GetMessageCount returns the MessageCount field value if set, zero value otherwise.
func (o *EmailMessageInfo) GetMessageCount() int32 {
	if o == nil || o.MessageCount == nil {
		var ret int32
		return ret
	}
	return *o.MessageCount
}

// GetMessageCountOk returns a tuple with the MessageCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailMessageInfo) GetMessageCountOk() (*int32, bool) {
	if o == nil || o.MessageCount == nil {
		return nil, false
	}
	return o.MessageCount, true
}

// HasMessageCount returns a boolean if a field has been set.
func (o *EmailMessageInfo) HasMessageCount() bool {
	if o != nil && o.MessageCount != nil {
		return true
	}

	return false
}

// SetMessageCount gets a reference to the given int32 and assigns it to the MessageCount field.
func (o *EmailMessageInfo) SetMessageCount(v int32) {
	o.MessageCount = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *EmailMessageInfo) GetMessageId() string {
	if o == nil || o.MessageId == nil {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailMessageInfo) GetMessageIdOk() (*string, bool) {
	if o == nil || o.MessageId == nil {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *EmailMessageInfo) HasMessageId() bool {
	if o != nil && o.MessageId != nil {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *EmailMessageInfo) SetMessageId(v string) {
	o.MessageId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailMessageInfo) GetStatus() EmailMessageStatus {
	if o == nil || o.Status == nil {
		var ret EmailMessageStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailMessageInfo) GetStatusOk() (*EmailMessageStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailMessageInfo) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given EmailMessageStatus and assigns it to the Status field.
func (o *EmailMessageInfo) SetStatus(v EmailMessageStatus) {
	o.Status = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *EmailMessageInfo) GetTo() string {
	if o == nil || o.To == nil {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailMessageInfo) GetToOk() (*string, bool) {
	if o == nil || o.To == nil {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *EmailMessageInfo) HasTo() bool {
	if o != nil && o.To != nil {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *EmailMessageInfo) SetTo(v string) {
	o.To = &v
}

func (o EmailMessageInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MessageCount != nil {
		toSerialize["messageCount"] = o.MessageCount
	}
	if o.MessageId != nil {
		toSerialize["messageId"] = o.MessageId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.To != nil {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullableEmailMessageInfo struct {
	value *EmailMessageInfo
	isSet bool
}

func (v NullableEmailMessageInfo) Get() *EmailMessageInfo {
	return v.value
}

func (v *NullableEmailMessageInfo) Set(val *EmailMessageInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailMessageInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailMessageInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailMessageInfo(val *EmailMessageInfo) *NullableEmailMessageInfo {
	return &NullableEmailMessageInfo{value: val, isSet: true}
}

func (v NullableEmailMessageInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailMessageInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
