/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppApiFailoverMessage Array of messages that will be sent.
type WhatsAppApiFailoverMessage struct {
	// Registered WhatsApp sender number. Must be in international format.
	From string `json:"from"`
	// Message recipient number. Must be in international format.
	To string `json:"to"`
	// The ID that uniquely identifies the message sent.
	MessageId *string                            `json:"messageId,omitempty"`
	Content   WhatsAppTemplateWhatsAppApiContent `json:"content"`
	// Custom client data that will be included in Delivery Report.
	CallbackData *string              `json:"callbackData,omitempty"`
	SmsFailover  *WhatsAppApiFailover `json:"smsFailover,omitempty"`
}

// NewWhatsAppApiFailoverMessage instantiates a new WhatsAppApiFailoverMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppApiFailoverMessage(from string, to string, content WhatsAppTemplateWhatsAppApiContent) *WhatsAppApiFailoverMessage {
	this := WhatsAppApiFailoverMessage{}
	this.From = from
	this.To = to
	this.Content = content
	return &this
}

// NewWhatsAppApiFailoverMessageWithDefaults instantiates a new WhatsAppApiFailoverMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppApiFailoverMessageWithDefaults() *WhatsAppApiFailoverMessage {
	this := WhatsAppApiFailoverMessage{}
	return &this
}

// GetFrom returns the From field value
func (o *WhatsAppApiFailoverMessage) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *WhatsAppApiFailoverMessage) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *WhatsAppApiFailoverMessage) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *WhatsAppApiFailoverMessage) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *WhatsAppApiFailoverMessage) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *WhatsAppApiFailoverMessage) SetTo(v string) {
	o.To = v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *WhatsAppApiFailoverMessage) GetMessageId() string {
	if o == nil || o.MessageId == nil {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppApiFailoverMessage) GetMessageIdOk() (*string, bool) {
	if o == nil || o.MessageId == nil {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *WhatsAppApiFailoverMessage) HasMessageId() bool {
	if o != nil && o.MessageId != nil {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *WhatsAppApiFailoverMessage) SetMessageId(v string) {
	o.MessageId = &v
}

// GetContent returns the Content field value
func (o *WhatsAppApiFailoverMessage) GetContent() WhatsAppTemplateWhatsAppApiContent {
	if o == nil {
		var ret WhatsAppTemplateWhatsAppApiContent
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *WhatsAppApiFailoverMessage) GetContentOk() (*WhatsAppTemplateWhatsAppApiContent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *WhatsAppApiFailoverMessage) SetContent(v WhatsAppTemplateWhatsAppApiContent) {
	o.Content = v
}

// GetCallbackData returns the CallbackData field value if set, zero value otherwise.
func (o *WhatsAppApiFailoverMessage) GetCallbackData() string {
	if o == nil || o.CallbackData == nil {
		var ret string
		return ret
	}
	return *o.CallbackData
}

// GetCallbackDataOk returns a tuple with the CallbackData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppApiFailoverMessage) GetCallbackDataOk() (*string, bool) {
	if o == nil || o.CallbackData == nil {
		return nil, false
	}
	return o.CallbackData, true
}

// HasCallbackData returns a boolean if a field has been set.
func (o *WhatsAppApiFailoverMessage) HasCallbackData() bool {
	if o != nil && o.CallbackData != nil {
		return true
	}

	return false
}

// SetCallbackData gets a reference to the given string and assigns it to the CallbackData field.
func (o *WhatsAppApiFailoverMessage) SetCallbackData(v string) {
	o.CallbackData = &v
}

// GetSmsFailover returns the SmsFailover field value if set, zero value otherwise.
func (o *WhatsAppApiFailoverMessage) GetSmsFailover() WhatsAppApiFailover {
	if o == nil || o.SmsFailover == nil {
		var ret WhatsAppApiFailover
		return ret
	}
	return *o.SmsFailover
}

// GetSmsFailoverOk returns a tuple with the SmsFailover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppApiFailoverMessage) GetSmsFailoverOk() (*WhatsAppApiFailover, bool) {
	if o == nil || o.SmsFailover == nil {
		return nil, false
	}
	return o.SmsFailover, true
}

// HasSmsFailover returns a boolean if a field has been set.
func (o *WhatsAppApiFailoverMessage) HasSmsFailover() bool {
	if o != nil && o.SmsFailover != nil {
		return true
	}

	return false
}

// SetSmsFailover gets a reference to the given WhatsAppApiFailover and assigns it to the SmsFailover field.
func (o *WhatsAppApiFailoverMessage) SetSmsFailover(v WhatsAppApiFailover) {
	o.SmsFailover = &v
}

func (o WhatsAppApiFailoverMessage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["from"] = o.From
	}
	if true {
		toSerialize["to"] = o.To
	}
	if o.MessageId != nil {
		toSerialize["messageId"] = o.MessageId
	}
	if true {
		toSerialize["content"] = o.Content
	}
	if o.CallbackData != nil {
		toSerialize["callbackData"] = o.CallbackData
	}
	if o.SmsFailover != nil {
		toSerialize["smsFailover"] = o.SmsFailover
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppApiFailoverMessage struct {
	value *WhatsAppApiFailoverMessage
	isSet bool
}

func (v NullableWhatsAppApiFailoverMessage) Get() *WhatsAppApiFailoverMessage {
	return v.value
}

func (v *NullableWhatsAppApiFailoverMessage) Set(val *WhatsAppApiFailoverMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppApiFailoverMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppApiFailoverMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppApiFailoverMessage(val *WhatsAppApiFailoverMessage) *NullableWhatsAppApiFailoverMessage {
	return &NullableWhatsAppApiFailoverMessage{value: val, isSet: true}
}

func (v NullableWhatsAppApiFailoverMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppApiFailoverMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
