/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppAddressWhatsAppApiContent Array of addresses information.
type WhatsAppAddressWhatsAppApiContent struct {
	// Street name.
	Street *string `json:"street,omitempty"`
	// City name.
	City *string `json:"city,omitempty"`
	// State name.
	State *string `json:"state,omitempty"`
	// Zip code value.
	Zip *string `json:"zip,omitempty"`
	// Country name.
	Country *string `json:"country,omitempty"`
	// Country code value.
	CountryCode *string `json:"countryCode,omitempty"`
	// Type of the address. Can be `HOME` or `WORK`.
	Type *string `json:"type,omitempty"`
}

// NewWhatsAppAddressWhatsAppApiContent instantiates a new WhatsAppAddressWhatsAppApiContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppAddressWhatsAppApiContent() *WhatsAppAddressWhatsAppApiContent {
	this := WhatsAppAddressWhatsAppApiContent{}
	return &this
}

// NewWhatsAppAddressWhatsAppApiContentWithDefaults instantiates a new WhatsAppAddressWhatsAppApiContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppAddressWhatsAppApiContentWithDefaults() *WhatsAppAddressWhatsAppApiContent {
	this := WhatsAppAddressWhatsAppApiContent{}
	return &this
}

// GetStreet returns the Street field value if set, zero value otherwise.
func (o *WhatsAppAddressWhatsAppApiContent) GetStreet() string {
	if o == nil || o.Street == nil {
		var ret string
		return ret
	}
	return *o.Street
}

// GetStreetOk returns a tuple with the Street field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppAddressWhatsAppApiContent) GetStreetOk() (*string, bool) {
	if o == nil || o.Street == nil {
		return nil, false
	}
	return o.Street, true
}

// HasStreet returns a boolean if a field has been set.
func (o *WhatsAppAddressWhatsAppApiContent) HasStreet() bool {
	if o != nil && o.Street != nil {
		return true
	}

	return false
}

// SetStreet gets a reference to the given string and assigns it to the Street field.
func (o *WhatsAppAddressWhatsAppApiContent) SetStreet(v string) {
	o.Street = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *WhatsAppAddressWhatsAppApiContent) GetCity() string {
	if o == nil || o.City == nil {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppAddressWhatsAppApiContent) GetCityOk() (*string, bool) {
	if o == nil || o.City == nil {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *WhatsAppAddressWhatsAppApiContent) HasCity() bool {
	if o != nil && o.City != nil {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *WhatsAppAddressWhatsAppApiContent) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *WhatsAppAddressWhatsAppApiContent) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppAddressWhatsAppApiContent) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *WhatsAppAddressWhatsAppApiContent) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *WhatsAppAddressWhatsAppApiContent) SetState(v string) {
	o.State = &v
}

// GetZip returns the Zip field value if set, zero value otherwise.
func (o *WhatsAppAddressWhatsAppApiContent) GetZip() string {
	if o == nil || o.Zip == nil {
		var ret string
		return ret
	}
	return *o.Zip
}

// GetZipOk returns a tuple with the Zip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppAddressWhatsAppApiContent) GetZipOk() (*string, bool) {
	if o == nil || o.Zip == nil {
		return nil, false
	}
	return o.Zip, true
}

// HasZip returns a boolean if a field has been set.
func (o *WhatsAppAddressWhatsAppApiContent) HasZip() bool {
	if o != nil && o.Zip != nil {
		return true
	}

	return false
}

// SetZip gets a reference to the given string and assigns it to the Zip field.
func (o *WhatsAppAddressWhatsAppApiContent) SetZip(v string) {
	o.Zip = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *WhatsAppAddressWhatsAppApiContent) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppAddressWhatsAppApiContent) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *WhatsAppAddressWhatsAppApiContent) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *WhatsAppAddressWhatsAppApiContent) SetCountry(v string) {
	o.Country = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *WhatsAppAddressWhatsAppApiContent) GetCountryCode() string {
	if o == nil || o.CountryCode == nil {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppAddressWhatsAppApiContent) GetCountryCodeOk() (*string, bool) {
	if o == nil || o.CountryCode == nil {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *WhatsAppAddressWhatsAppApiContent) HasCountryCode() bool {
	if o != nil && o.CountryCode != nil {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *WhatsAppAddressWhatsAppApiContent) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WhatsAppAddressWhatsAppApiContent) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppAddressWhatsAppApiContent) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WhatsAppAddressWhatsAppApiContent) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WhatsAppAddressWhatsAppApiContent) SetType(v string) {
	o.Type = &v
}

func (o WhatsAppAddressWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Street != nil {
		toSerialize["street"] = o.Street
	}
	if o.City != nil {
		toSerialize["city"] = o.City
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Zip != nil {
		toSerialize["zip"] = o.Zip
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	if o.CountryCode != nil {
		toSerialize["countryCode"] = o.CountryCode
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppAddressWhatsAppApiContent struct {
	value *WhatsAppAddressWhatsAppApiContent
	isSet bool
}

func (v NullableWhatsAppAddressWhatsAppApiContent) Get() *WhatsAppAddressWhatsAppApiContent {
	return v.value
}

func (v *NullableWhatsAppAddressWhatsAppApiContent) Set(val *WhatsAppAddressWhatsAppApiContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppAddressWhatsAppApiContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppAddressWhatsAppApiContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppAddressWhatsAppApiContent(val *WhatsAppAddressWhatsAppApiContent) *NullableWhatsAppAddressWhatsAppApiContent {
	return &NullableWhatsAppAddressWhatsAppApiContent{value: val, isSet: true}
}

func (v NullableWhatsAppAddressWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppAddressWhatsAppApiContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
