/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppTemplateTemplateApiResponse List of all templates for given sender.
type WhatsAppTemplateTemplateApiResponse struct {
	// Template ID.
	Id *string `json:"id,omitempty"`
	// Business account ID to which template belongs.
	BusinessAccountId *int64 `json:"businessAccountId,omitempty"`
	// Name of the template.
	Name *string `json:"name,omitempty"`
	// Template language, one template with same name can have multiple transliterations.
	Language *string `json:"language,omitempty"`
	// Status of the template.
	Status *string `json:"status,omitempty"`
	// Category of the template.
	Category  *string                                   `json:"category,omitempty"`
	Structure *WhatsAppTemplateTemplateStructureApiData `json:"structure,omitempty"`
}

// NewWhatsAppTemplateTemplateApiResponse instantiates a new WhatsAppTemplateTemplateApiResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppTemplateTemplateApiResponse() *WhatsAppTemplateTemplateApiResponse {
	this := WhatsAppTemplateTemplateApiResponse{}
	return &this
}

// NewWhatsAppTemplateTemplateApiResponseWithDefaults instantiates a new WhatsAppTemplateTemplateApiResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppTemplateTemplateApiResponseWithDefaults() *WhatsAppTemplateTemplateApiResponse {
	this := WhatsAppTemplateTemplateApiResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WhatsAppTemplateTemplateApiResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplateApiResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WhatsAppTemplateTemplateApiResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WhatsAppTemplateTemplateApiResponse) SetId(v string) {
	o.Id = &v
}

// GetBusinessAccountId returns the BusinessAccountId field value if set, zero value otherwise.
func (o *WhatsAppTemplateTemplateApiResponse) GetBusinessAccountId() int64 {
	if o == nil || o.BusinessAccountId == nil {
		var ret int64
		return ret
	}
	return *o.BusinessAccountId
}

// GetBusinessAccountIdOk returns a tuple with the BusinessAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplateApiResponse) GetBusinessAccountIdOk() (*int64, bool) {
	if o == nil || o.BusinessAccountId == nil {
		return nil, false
	}
	return o.BusinessAccountId, true
}

// HasBusinessAccountId returns a boolean if a field has been set.
func (o *WhatsAppTemplateTemplateApiResponse) HasBusinessAccountId() bool {
	if o != nil && o.BusinessAccountId != nil {
		return true
	}

	return false
}

// SetBusinessAccountId gets a reference to the given int64 and assigns it to the BusinessAccountId field.
func (o *WhatsAppTemplateTemplateApiResponse) SetBusinessAccountId(v int64) {
	o.BusinessAccountId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WhatsAppTemplateTemplateApiResponse) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplateApiResponse) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WhatsAppTemplateTemplateApiResponse) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WhatsAppTemplateTemplateApiResponse) SetName(v string) {
	o.Name = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *WhatsAppTemplateTemplateApiResponse) GetLanguage() string {
	if o == nil || o.Language == nil {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplateApiResponse) GetLanguageOk() (*string, bool) {
	if o == nil || o.Language == nil {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *WhatsAppTemplateTemplateApiResponse) HasLanguage() bool {
	if o != nil && o.Language != nil {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *WhatsAppTemplateTemplateApiResponse) SetLanguage(v string) {
	o.Language = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WhatsAppTemplateTemplateApiResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplateApiResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WhatsAppTemplateTemplateApiResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WhatsAppTemplateTemplateApiResponse) SetStatus(v string) {
	o.Status = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *WhatsAppTemplateTemplateApiResponse) GetCategory() string {
	if o == nil || o.Category == nil {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplateApiResponse) GetCategoryOk() (*string, bool) {
	if o == nil || o.Category == nil {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *WhatsAppTemplateTemplateApiResponse) HasCategory() bool {
	if o != nil && o.Category != nil {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *WhatsAppTemplateTemplateApiResponse) SetCategory(v string) {
	o.Category = &v
}

// GetStructure returns the Structure field value if set, zero value otherwise.
func (o *WhatsAppTemplateTemplateApiResponse) GetStructure() WhatsAppTemplateTemplateStructureApiData {
	if o == nil || o.Structure == nil {
		var ret WhatsAppTemplateTemplateStructureApiData
		return ret
	}
	return *o.Structure
}

// GetStructureOk returns a tuple with the Structure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplateApiResponse) GetStructureOk() (*WhatsAppTemplateTemplateStructureApiData, bool) {
	if o == nil || o.Structure == nil {
		return nil, false
	}
	return o.Structure, true
}

// HasStructure returns a boolean if a field has been set.
func (o *WhatsAppTemplateTemplateApiResponse) HasStructure() bool {
	if o != nil && o.Structure != nil {
		return true
	}

	return false
}

// SetStructure gets a reference to the given WhatsAppTemplateTemplateStructureApiData and assigns it to the Structure field.
func (o *WhatsAppTemplateTemplateApiResponse) SetStructure(v WhatsAppTemplateTemplateStructureApiData) {
	o.Structure = &v
}

func (o WhatsAppTemplateTemplateApiResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.BusinessAccountId != nil {
		toSerialize["businessAccountId"] = o.BusinessAccountId
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Language != nil {
		toSerialize["language"] = o.Language
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Category != nil {
		toSerialize["category"] = o.Category
	}
	if o.Structure != nil {
		toSerialize["structure"] = o.Structure
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppTemplateTemplateApiResponse struct {
	value *WhatsAppTemplateTemplateApiResponse
	isSet bool
}

func (v NullableWhatsAppTemplateTemplateApiResponse) Get() *WhatsAppTemplateTemplateApiResponse {
	return v.value
}

func (v *NullableWhatsAppTemplateTemplateApiResponse) Set(val *WhatsAppTemplateTemplateApiResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppTemplateTemplateApiResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppTemplateTemplateApiResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppTemplateTemplateApiResponse(val *WhatsAppTemplateTemplateApiResponse) *NullableWhatsAppTemplateTemplateApiResponse {
	return &NullableWhatsAppTemplateTemplateApiResponse{value: val, isSet: true}
}

func (v NullableWhatsAppTemplateTemplateApiResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppTemplateTemplateApiResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
