/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// EmailBulkUpdateStatusResponse struct for EmailBulkUpdateStatusResponse
type EmailBulkUpdateStatusResponse struct {
	BulkId *string          `json:"bulkId,omitempty"`
	Status *EmailBulkStatus `json:"status,omitempty"`
}

// NewEmailBulkUpdateStatusResponse instantiates a new EmailBulkUpdateStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailBulkUpdateStatusResponse() *EmailBulkUpdateStatusResponse {
	this := EmailBulkUpdateStatusResponse{}
	return &this
}

// NewEmailBulkUpdateStatusResponseWithDefaults instantiates a new EmailBulkUpdateStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailBulkUpdateStatusResponseWithDefaults() *EmailBulkUpdateStatusResponse {
	this := EmailBulkUpdateStatusResponse{}
	return &this
}

// GetBulkId returns the BulkId field value if set, zero value otherwise.
func (o *EmailBulkUpdateStatusResponse) GetBulkId() string {
	if o == nil || o.BulkId == nil {
		var ret string
		return ret
	}
	return *o.BulkId
}

// GetBulkIdOk returns a tuple with the BulkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailBulkUpdateStatusResponse) GetBulkIdOk() (*string, bool) {
	if o == nil || o.BulkId == nil {
		return nil, false
	}
	return o.BulkId, true
}

// HasBulkId returns a boolean if a field has been set.
func (o *EmailBulkUpdateStatusResponse) HasBulkId() bool {
	if o != nil && o.BulkId != nil {
		return true
	}

	return false
}

// SetBulkId gets a reference to the given string and assigns it to the BulkId field.
func (o *EmailBulkUpdateStatusResponse) SetBulkId(v string) {
	o.BulkId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailBulkUpdateStatusResponse) GetStatus() EmailBulkStatus {
	if o == nil || o.Status == nil {
		var ret EmailBulkStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailBulkUpdateStatusResponse) GetStatusOk() (*EmailBulkStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailBulkUpdateStatusResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given EmailBulkStatus and assigns it to the Status field.
func (o *EmailBulkUpdateStatusResponse) SetStatus(v EmailBulkStatus) {
	o.Status = &v
}

func (o EmailBulkUpdateStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BulkId != nil {
		toSerialize["bulkId"] = o.BulkId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableEmailBulkUpdateStatusResponse struct {
	value *EmailBulkUpdateStatusResponse
	isSet bool
}

func (v NullableEmailBulkUpdateStatusResponse) Get() *EmailBulkUpdateStatusResponse {
	return v.value
}

func (v *NullableEmailBulkUpdateStatusResponse) Set(val *EmailBulkUpdateStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailBulkUpdateStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailBulkUpdateStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailBulkUpdateStatusResponse(val *EmailBulkUpdateStatusResponse) *NullableEmailBulkUpdateStatusResponse {
	return &NullableEmailBulkUpdateStatusResponse{value: val, isSet: true}
}

func (v NullableEmailBulkUpdateStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailBulkUpdateStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
