/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppTemplatePhoneNumberButtonApiData struct for WhatsAppTemplatePhoneNumberButtonApiData
type WhatsAppTemplatePhoneNumberButtonApiData struct {
	WhatsAppTemplateButtonApiData
	// Button text.
	Text string `json:"text"`
	// Phone number to which a phone call would be placed by end-user when hitting the button.
	PhoneNumber string `json:"phoneNumber"`
}

// NewWhatsAppTemplatePhoneNumberButtonApiData instantiates a new WhatsAppTemplatePhoneNumberButtonApiData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppTemplatePhoneNumberButtonApiData(text string, phoneNumber string) *WhatsAppTemplatePhoneNumberButtonApiData {
	this := WhatsAppTemplatePhoneNumberButtonApiData{}
	this.Text = text
	this.PhoneNumber = phoneNumber
	return &this
}

// NewWhatsAppTemplatePhoneNumberButtonApiDataWithDefaults instantiates a new WhatsAppTemplatePhoneNumberButtonApiData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppTemplatePhoneNumberButtonApiDataWithDefaults() *WhatsAppTemplatePhoneNumberButtonApiData {
	this := WhatsAppTemplatePhoneNumberButtonApiData{}
	return &this
}

// GetText returns the Text field value
func (o *WhatsAppTemplatePhoneNumberButtonApiData) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplatePhoneNumberButtonApiData) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *WhatsAppTemplatePhoneNumberButtonApiData) SetText(v string) {
	o.Text = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *WhatsAppTemplatePhoneNumberButtonApiData) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplatePhoneNumberButtonApiData) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *WhatsAppTemplatePhoneNumberButtonApiData) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

func (o WhatsAppTemplatePhoneNumberButtonApiData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedWhatsAppTemplateButtonApiData, errWhatsAppTemplateButtonApiData := json.Marshal(o.WhatsAppTemplateButtonApiData)
	if errWhatsAppTemplateButtonApiData != nil {
		return []byte{}, errWhatsAppTemplateButtonApiData
	}
	errWhatsAppTemplateButtonApiData = json.Unmarshal([]byte(serializedWhatsAppTemplateButtonApiData), &toSerialize)
	if errWhatsAppTemplateButtonApiData != nil {
		return []byte{}, errWhatsAppTemplateButtonApiData
	}
	if true {
		toSerialize["text"] = o.Text
	}
	if true {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppTemplatePhoneNumberButtonApiData struct {
	value *WhatsAppTemplatePhoneNumberButtonApiData
	isSet bool
}

func (v NullableWhatsAppTemplatePhoneNumberButtonApiData) Get() *WhatsAppTemplatePhoneNumberButtonApiData {
	return v.value
}

func (v *NullableWhatsAppTemplatePhoneNumberButtonApiData) Set(val *WhatsAppTemplatePhoneNumberButtonApiData) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppTemplatePhoneNumberButtonApiData) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppTemplatePhoneNumberButtonApiData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppTemplatePhoneNumberButtonApiData(val *WhatsAppTemplatePhoneNumberButtonApiData) *NullableWhatsAppTemplatePhoneNumberButtonApiData {
	return &NullableWhatsAppTemplatePhoneNumberButtonApiData{value: val, isSet: true}
}

func (v NullableWhatsAppTemplatePhoneNumberButtonApiData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppTemplatePhoneNumberButtonApiData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
