/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppPhoneWhatsAppApiContent Array of phones information.
type WhatsAppPhoneWhatsAppApiContent struct {
	// Contact's phone number.
	Phone *string `json:"phone,omitempty"`
	// Type of the phone number. Can be `CELL`, `MAIN`, `IPHONE`, `HOME` or `WORK`.
	Type *string `json:"type,omitempty"`
	// Contact's WhatsApp ID.
	WaId *string `json:"waId,omitempty"`
}

// NewWhatsAppPhoneWhatsAppApiContent instantiates a new WhatsAppPhoneWhatsAppApiContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppPhoneWhatsAppApiContent() *WhatsAppPhoneWhatsAppApiContent {
	this := WhatsAppPhoneWhatsAppApiContent{}
	return &this
}

// NewWhatsAppPhoneWhatsAppApiContentWithDefaults instantiates a new WhatsAppPhoneWhatsAppApiContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppPhoneWhatsAppApiContentWithDefaults() *WhatsAppPhoneWhatsAppApiContent {
	this := WhatsAppPhoneWhatsAppApiContent{}
	return &this
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *WhatsAppPhoneWhatsAppApiContent) GetPhone() string {
	if o == nil || o.Phone == nil {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppPhoneWhatsAppApiContent) GetPhoneOk() (*string, bool) {
	if o == nil || o.Phone == nil {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *WhatsAppPhoneWhatsAppApiContent) HasPhone() bool {
	if o != nil && o.Phone != nil {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *WhatsAppPhoneWhatsAppApiContent) SetPhone(v string) {
	o.Phone = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WhatsAppPhoneWhatsAppApiContent) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppPhoneWhatsAppApiContent) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WhatsAppPhoneWhatsAppApiContent) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WhatsAppPhoneWhatsAppApiContent) SetType(v string) {
	o.Type = &v
}

// GetWaId returns the WaId field value if set, zero value otherwise.
func (o *WhatsAppPhoneWhatsAppApiContent) GetWaId() string {
	if o == nil || o.WaId == nil {
		var ret string
		return ret
	}
	return *o.WaId
}

// GetWaIdOk returns a tuple with the WaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppPhoneWhatsAppApiContent) GetWaIdOk() (*string, bool) {
	if o == nil || o.WaId == nil {
		return nil, false
	}
	return o.WaId, true
}

// HasWaId returns a boolean if a field has been set.
func (o *WhatsAppPhoneWhatsAppApiContent) HasWaId() bool {
	if o != nil && o.WaId != nil {
		return true
	}

	return false
}

// SetWaId gets a reference to the given string and assigns it to the WaId field.
func (o *WhatsAppPhoneWhatsAppApiContent) SetWaId(v string) {
	o.WaId = &v
}

func (o WhatsAppPhoneWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Phone != nil {
		toSerialize["phone"] = o.Phone
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.WaId != nil {
		toSerialize["waId"] = o.WaId
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppPhoneWhatsAppApiContent struct {
	value *WhatsAppPhoneWhatsAppApiContent
	isSet bool
}

func (v NullableWhatsAppPhoneWhatsAppApiContent) Get() *WhatsAppPhoneWhatsAppApiContent {
	return v.value
}

func (v *NullableWhatsAppPhoneWhatsAppApiContent) Set(val *WhatsAppPhoneWhatsAppApiContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppPhoneWhatsAppApiContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppPhoneWhatsAppApiContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppPhoneWhatsAppApiContent(val *WhatsAppPhoneWhatsAppApiContent) *NullableWhatsAppPhoneWhatsAppApiContent {
	return &NullableWhatsAppPhoneWhatsAppApiContent{value: val, isSet: true}
}

func (v NullableWhatsAppPhoneWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppPhoneWhatsAppApiContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
