/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppTemplateVideoHeaderApiData struct for WhatsAppTemplateVideoHeaderApiData
type WhatsAppTemplateVideoHeaderApiData struct {
	WhatsAppTemplateHeaderApiData
}

// NewWhatsAppTemplateVideoHeaderApiData instantiates a new WhatsAppTemplateVideoHeaderApiData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppTemplateVideoHeaderApiData() *WhatsAppTemplateVideoHeaderApiData {
	this := WhatsAppTemplateVideoHeaderApiData{}
	return &this
}

// NewWhatsAppTemplateVideoHeaderApiDataWithDefaults instantiates a new WhatsAppTemplateVideoHeaderApiData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppTemplateVideoHeaderApiDataWithDefaults() *WhatsAppTemplateVideoHeaderApiData {
	this := WhatsAppTemplateVideoHeaderApiData{}
	return &this
}

func (o WhatsAppTemplateVideoHeaderApiData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedWhatsAppTemplateHeaderApiData, errWhatsAppTemplateHeaderApiData := json.Marshal(o.WhatsAppTemplateHeaderApiData)
	if errWhatsAppTemplateHeaderApiData != nil {
		return []byte{}, errWhatsAppTemplateHeaderApiData
	}
	errWhatsAppTemplateHeaderApiData = json.Unmarshal([]byte(serializedWhatsAppTemplateHeaderApiData), &toSerialize)
	if errWhatsAppTemplateHeaderApiData != nil {
		return []byte{}, errWhatsAppTemplateHeaderApiData
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppTemplateVideoHeaderApiData struct {
	value *WhatsAppTemplateVideoHeaderApiData
	isSet bool
}

func (v NullableWhatsAppTemplateVideoHeaderApiData) Get() *WhatsAppTemplateVideoHeaderApiData {
	return v.value
}

func (v *NullableWhatsAppTemplateVideoHeaderApiData) Set(val *WhatsAppTemplateVideoHeaderApiData) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppTemplateVideoHeaderApiData) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppTemplateVideoHeaderApiData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppTemplateVideoHeaderApiData(val *WhatsAppTemplateVideoHeaderApiData) *NullableWhatsAppTemplateVideoHeaderApiData {
	return &NullableWhatsAppTemplateVideoHeaderApiData{value: val, isSet: true}
}

func (v NullableWhatsAppTemplateVideoHeaderApiData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppTemplateVideoHeaderApiData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
