/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// EmailValidationRequest struct for EmailValidationRequest
type EmailValidationRequest struct {
	To string `json:"to"`
}

// NewEmailValidationRequest instantiates a new EmailValidationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailValidationRequest(to string) *EmailValidationRequest {
	this := EmailValidationRequest{}
	this.To = to
	return &this
}

// NewEmailValidationRequestWithDefaults instantiates a new EmailValidationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailValidationRequestWithDefaults() *EmailValidationRequest {
	this := EmailValidationRequest{}
	return &this
}

// GetTo returns the To field value
func (o *EmailValidationRequest) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *EmailValidationRequest) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *EmailValidationRequest) SetTo(v string) {
	o.To = v
}

func (o EmailValidationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullableEmailValidationRequest struct {
	value *EmailValidationRequest
	isSet bool
}

func (v NullableEmailValidationRequest) Get() *EmailValidationRequest {
	return v.value
}

func (v *NullableEmailValidationRequest) Set(val *EmailValidationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailValidationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailValidationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailValidationRequest(val *EmailValidationRequest) *NullableEmailValidationRequest {
	return &NullableEmailValidationRequest{value: val, isSet: true}
}

func (v NullableEmailValidationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailValidationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
