/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// EmailBulkScheduleResponse struct for EmailBulkScheduleResponse
type EmailBulkScheduleResponse struct {
	Bulks          *[]EmailBulkInfo `json:"bulks,omitempty"`
	ExternalBulkId *string          `json:"externalBulkId,omitempty"`
}

// NewEmailBulkScheduleResponse instantiates a new EmailBulkScheduleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailBulkScheduleResponse() *EmailBulkScheduleResponse {
	this := EmailBulkScheduleResponse{}
	return &this
}

// NewEmailBulkScheduleResponseWithDefaults instantiates a new EmailBulkScheduleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailBulkScheduleResponseWithDefaults() *EmailBulkScheduleResponse {
	this := EmailBulkScheduleResponse{}
	return &this
}

// GetBulks returns the Bulks field value if set, zero value otherwise.
func (o *EmailBulkScheduleResponse) GetBulks() []EmailBulkInfo {
	if o == nil || o.Bulks == nil {
		var ret []EmailBulkInfo
		return ret
	}
	return *o.Bulks
}

// GetBulksOk returns a tuple with the Bulks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailBulkScheduleResponse) GetBulksOk() (*[]EmailBulkInfo, bool) {
	if o == nil || o.Bulks == nil {
		return nil, false
	}
	return o.Bulks, true
}

// HasBulks returns a boolean if a field has been set.
func (o *EmailBulkScheduleResponse) HasBulks() bool {
	if o != nil && o.Bulks != nil {
		return true
	}

	return false
}

// SetBulks gets a reference to the given []EmailBulkInfo and assigns it to the Bulks field.
func (o *EmailBulkScheduleResponse) SetBulks(v []EmailBulkInfo) {
	o.Bulks = &v
}

// GetExternalBulkId returns the ExternalBulkId field value if set, zero value otherwise.
func (o *EmailBulkScheduleResponse) GetExternalBulkId() string {
	if o == nil || o.ExternalBulkId == nil {
		var ret string
		return ret
	}
	return *o.ExternalBulkId
}

// GetExternalBulkIdOk returns a tuple with the ExternalBulkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailBulkScheduleResponse) GetExternalBulkIdOk() (*string, bool) {
	if o == nil || o.ExternalBulkId == nil {
		return nil, false
	}
	return o.ExternalBulkId, true
}

// HasExternalBulkId returns a boolean if a field has been set.
func (o *EmailBulkScheduleResponse) HasExternalBulkId() bool {
	if o != nil && o.ExternalBulkId != nil {
		return true
	}

	return false
}

// SetExternalBulkId gets a reference to the given string and assigns it to the ExternalBulkId field.
func (o *EmailBulkScheduleResponse) SetExternalBulkId(v string) {
	o.ExternalBulkId = &v
}

func (o EmailBulkScheduleResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Bulks != nil {
		toSerialize["bulks"] = o.Bulks
	}
	if o.ExternalBulkId != nil {
		toSerialize["externalBulkId"] = o.ExternalBulkId
	}
	return json.Marshal(toSerialize)
}

type NullableEmailBulkScheduleResponse struct {
	value *EmailBulkScheduleResponse
	isSet bool
}

func (v NullableEmailBulkScheduleResponse) Get() *EmailBulkScheduleResponse {
	return v.value
}

func (v *NullableEmailBulkScheduleResponse) Set(val *EmailBulkScheduleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailBulkScheduleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailBulkScheduleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailBulkScheduleResponse(val *EmailBulkScheduleResponse) *NullableEmailBulkScheduleResponse {
	return &NullableEmailBulkScheduleResponse{value: val, isSet: true}
}

func (v NullableEmailBulkScheduleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailBulkScheduleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
