/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppTemplateVideoHeaderWhatsAppApiContent struct for WhatsAppTemplateVideoHeaderWhatsAppApiContent
type WhatsAppTemplateVideoHeaderWhatsAppApiContent struct {
	WhatsAppTemplateHeaderWhatsAppApiContent
	// URL of a video sent in the header. It is expected to be a valid URL starting with `https://`, `http://` or `ftp://`. Supported video types are `MP4`, `3GPP`. Maximum video size is 16MB.
	MediaUrl string `json:"mediaUrl"`
}

// NewWhatsAppTemplateVideoHeaderWhatsAppApiContent instantiates a new WhatsAppTemplateVideoHeaderWhatsAppApiContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppTemplateVideoHeaderWhatsAppApiContent(mediaUrl string, type_ string) *WhatsAppTemplateVideoHeaderWhatsAppApiContent {
	this := WhatsAppTemplateVideoHeaderWhatsAppApiContent{}
	this.Type = type_
	this.MediaUrl = mediaUrl
	return &this
}

// NewWhatsAppTemplateVideoHeaderWhatsAppApiContentWithDefaults instantiates a new WhatsAppTemplateVideoHeaderWhatsAppApiContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppTemplateVideoHeaderWhatsAppApiContentWithDefaults() *WhatsAppTemplateVideoHeaderWhatsAppApiContent {
	this := WhatsAppTemplateVideoHeaderWhatsAppApiContent{}
	return &this
}

// GetMediaUrl returns the MediaUrl field value
func (o *WhatsAppTemplateVideoHeaderWhatsAppApiContent) GetMediaUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MediaUrl
}

// GetMediaUrlOk returns a tuple with the MediaUrl field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateVideoHeaderWhatsAppApiContent) GetMediaUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MediaUrl, true
}

// SetMediaUrl sets field value
func (o *WhatsAppTemplateVideoHeaderWhatsAppApiContent) SetMediaUrl(v string) {
	o.MediaUrl = v
}

func (o WhatsAppTemplateVideoHeaderWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedWhatsAppTemplateHeaderWhatsAppApiContent, errWhatsAppTemplateHeaderWhatsAppApiContent := json.Marshal(o.WhatsAppTemplateHeaderWhatsAppApiContent)
	if errWhatsAppTemplateHeaderWhatsAppApiContent != nil {
		return []byte{}, errWhatsAppTemplateHeaderWhatsAppApiContent
	}
	errWhatsAppTemplateHeaderWhatsAppApiContent = json.Unmarshal([]byte(serializedWhatsAppTemplateHeaderWhatsAppApiContent), &toSerialize)
	if errWhatsAppTemplateHeaderWhatsAppApiContent != nil {
		return []byte{}, errWhatsAppTemplateHeaderWhatsAppApiContent
	}
	if true {
		toSerialize["mediaUrl"] = o.MediaUrl
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent struct {
	value *WhatsAppTemplateVideoHeaderWhatsAppApiContent
	isSet bool
}

func (v NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent) Get() *WhatsAppTemplateVideoHeaderWhatsAppApiContent {
	return v.value
}

func (v *NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent) Set(val *WhatsAppTemplateVideoHeaderWhatsAppApiContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppTemplateVideoHeaderWhatsAppApiContent(val *WhatsAppTemplateVideoHeaderWhatsAppApiContent) *NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent {
	return &NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent{value: val, isSet: true}
}

func (v NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppTemplateVideoHeaderWhatsAppApiContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
