/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppLocationWhatsAppApiContent Content of the message that will be sent.
type WhatsAppLocationWhatsAppApiContent struct {
	// Latitude of a location sent in the WhatsApp message.
	Latitude float64 `json:"latitude"`
	// Longitude of a location sent in the WhatsApp message.
	Longitude float64 `json:"longitude"`
	// Location name.
	Name *string `json:"name,omitempty"`
	// Location address.
	Address *string `json:"address,omitempty"`
}

// NewWhatsAppLocationWhatsAppApiContent instantiates a new WhatsAppLocationWhatsAppApiContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppLocationWhatsAppApiContent(latitude float64, longitude float64) *WhatsAppLocationWhatsAppApiContent {
	this := WhatsAppLocationWhatsAppApiContent{}
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewWhatsAppLocationWhatsAppApiContentWithDefaults instantiates a new WhatsAppLocationWhatsAppApiContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppLocationWhatsAppApiContentWithDefaults() *WhatsAppLocationWhatsAppApiContent {
	this := WhatsAppLocationWhatsAppApiContent{}
	return &this
}

// GetLatitude returns the Latitude field value
func (o *WhatsAppLocationWhatsAppApiContent) GetLatitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *WhatsAppLocationWhatsAppApiContent) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *WhatsAppLocationWhatsAppApiContent) SetLatitude(v float64) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *WhatsAppLocationWhatsAppApiContent) GetLongitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *WhatsAppLocationWhatsAppApiContent) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *WhatsAppLocationWhatsAppApiContent) SetLongitude(v float64) {
	o.Longitude = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *WhatsAppLocationWhatsAppApiContent) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppLocationWhatsAppApiContent) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *WhatsAppLocationWhatsAppApiContent) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *WhatsAppLocationWhatsAppApiContent) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *WhatsAppLocationWhatsAppApiContent) GetAddress() string {
	if o == nil || o.Address == nil {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppLocationWhatsAppApiContent) GetAddressOk() (*string, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *WhatsAppLocationWhatsAppApiContent) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *WhatsAppLocationWhatsAppApiContent) SetAddress(v string) {
	o.Address = &v
}

func (o WhatsAppLocationWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["latitude"] = o.Latitude
	}
	if true {
		toSerialize["longitude"] = o.Longitude
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppLocationWhatsAppApiContent struct {
	value *WhatsAppLocationWhatsAppApiContent
	isSet bool
}

func (v NullableWhatsAppLocationWhatsAppApiContent) Get() *WhatsAppLocationWhatsAppApiContent {
	return v.value
}

func (v *NullableWhatsAppLocationWhatsAppApiContent) Set(val *WhatsAppLocationWhatsAppApiContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppLocationWhatsAppApiContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppLocationWhatsAppApiContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppLocationWhatsAppApiContent(val *WhatsAppLocationWhatsAppApiContent) *NullableWhatsAppLocationWhatsAppApiContent {
	return &NullableWhatsAppLocationWhatsAppApiContent{value: val, isSet: true}
}

func (v NullableWhatsAppLocationWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppLocationWhatsAppApiContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
