/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppTemplateTemplatePublicApiRequest struct for WhatsAppTemplateTemplatePublicApiRequest
type WhatsAppTemplateTemplatePublicApiRequest struct {
	// Template name. Must only contain lowercase alphanumeric characters and underscores.
	Name string `json:"name"`
	// The language code or locale to use. Multiple templates with different language codes can be registered under the same template name.
	Language string `json:"language"`
	// Category of the template.
	Category  string                                   `json:"category"`
	Structure WhatsAppTemplateTemplateStructureApiData `json:"structure"`
}

// NewWhatsAppTemplateTemplatePublicApiRequest instantiates a new WhatsAppTemplateTemplatePublicApiRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppTemplateTemplatePublicApiRequest(name string, language string, category string, structure WhatsAppTemplateTemplateStructureApiData) *WhatsAppTemplateTemplatePublicApiRequest {
	this := WhatsAppTemplateTemplatePublicApiRequest{}
	this.Name = name
	this.Language = language
	this.Category = category
	this.Structure = structure
	return &this
}

// NewWhatsAppTemplateTemplatePublicApiRequestWithDefaults instantiates a new WhatsAppTemplateTemplatePublicApiRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppTemplateTemplatePublicApiRequestWithDefaults() *WhatsAppTemplateTemplatePublicApiRequest {
	this := WhatsAppTemplateTemplatePublicApiRequest{}
	return &this
}

// GetName returns the Name field value
func (o *WhatsAppTemplateTemplatePublicApiRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplatePublicApiRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WhatsAppTemplateTemplatePublicApiRequest) SetName(v string) {
	o.Name = v
}

// GetLanguage returns the Language field value
func (o *WhatsAppTemplateTemplatePublicApiRequest) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplatePublicApiRequest) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *WhatsAppTemplateTemplatePublicApiRequest) SetLanguage(v string) {
	o.Language = v
}

// GetCategory returns the Category field value
func (o *WhatsAppTemplateTemplatePublicApiRequest) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplatePublicApiRequest) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *WhatsAppTemplateTemplatePublicApiRequest) SetCategory(v string) {
	o.Category = v
}

// GetStructure returns the Structure field value
func (o *WhatsAppTemplateTemplatePublicApiRequest) GetStructure() WhatsAppTemplateTemplateStructureApiData {
	if o == nil {
		var ret WhatsAppTemplateTemplateStructureApiData
		return ret
	}

	return o.Structure
}

// GetStructureOk returns a tuple with the Structure field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplatePublicApiRequest) GetStructureOk() (*WhatsAppTemplateTemplateStructureApiData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Structure, true
}

// SetStructure sets field value
func (o *WhatsAppTemplateTemplatePublicApiRequest) SetStructure(v WhatsAppTemplateTemplateStructureApiData) {
	o.Structure = v
}

func (o WhatsAppTemplateTemplatePublicApiRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["language"] = o.Language
	}
	if true {
		toSerialize["category"] = o.Category
	}
	if true {
		toSerialize["structure"] = o.Structure
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppTemplateTemplatePublicApiRequest struct {
	value *WhatsAppTemplateTemplatePublicApiRequest
	isSet bool
}

func (v NullableWhatsAppTemplateTemplatePublicApiRequest) Get() *WhatsAppTemplateTemplatePublicApiRequest {
	return v.value
}

func (v *NullableWhatsAppTemplateTemplatePublicApiRequest) Set(val *WhatsAppTemplateTemplatePublicApiRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppTemplateTemplatePublicApiRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppTemplateTemplatePublicApiRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppTemplateTemplatePublicApiRequest(val *WhatsAppTemplateTemplatePublicApiRequest) *NullableWhatsAppTemplateTemplatePublicApiRequest {
	return &NullableWhatsAppTemplateTemplatePublicApiRequest{value: val, isSet: true}
}

func (v NullableWhatsAppTemplateTemplatePublicApiRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppTemplateTemplatePublicApiRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
