/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppTemplateTemplatesApiResponse struct for WhatsAppTemplateTemplatesApiResponse
type WhatsAppTemplateTemplatesApiResponse struct {
	// List of all templates for given sender.
	Templates *[]WhatsAppTemplateTemplateApiResponse `json:"templates,omitempty"`
}

// NewWhatsAppTemplateTemplatesApiResponse instantiates a new WhatsAppTemplateTemplatesApiResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppTemplateTemplatesApiResponse() *WhatsAppTemplateTemplatesApiResponse {
	this := WhatsAppTemplateTemplatesApiResponse{}
	return &this
}

// NewWhatsAppTemplateTemplatesApiResponseWithDefaults instantiates a new WhatsAppTemplateTemplatesApiResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppTemplateTemplatesApiResponseWithDefaults() *WhatsAppTemplateTemplatesApiResponse {
	this := WhatsAppTemplateTemplatesApiResponse{}
	return &this
}

// GetTemplates returns the Templates field value if set, zero value otherwise.
func (o *WhatsAppTemplateTemplatesApiResponse) GetTemplates() []WhatsAppTemplateTemplateApiResponse {
	if o == nil || o.Templates == nil {
		var ret []WhatsAppTemplateTemplateApiResponse
		return ret
	}
	return *o.Templates
}

// GetTemplatesOk returns a tuple with the Templates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateTemplatesApiResponse) GetTemplatesOk() (*[]WhatsAppTemplateTemplateApiResponse, bool) {
	if o == nil || o.Templates == nil {
		return nil, false
	}
	return o.Templates, true
}

// HasTemplates returns a boolean if a field has been set.
func (o *WhatsAppTemplateTemplatesApiResponse) HasTemplates() bool {
	if o != nil && o.Templates != nil {
		return true
	}

	return false
}

// SetTemplates gets a reference to the given []WhatsAppTemplateTemplateApiResponse and assigns it to the Templates field.
func (o *WhatsAppTemplateTemplatesApiResponse) SetTemplates(v []WhatsAppTemplateTemplateApiResponse) {
	o.Templates = &v
}

func (o WhatsAppTemplateTemplatesApiResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Templates != nil {
		toSerialize["templates"] = o.Templates
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppTemplateTemplatesApiResponse struct {
	value *WhatsAppTemplateTemplatesApiResponse
	isSet bool
}

func (v NullableWhatsAppTemplateTemplatesApiResponse) Get() *WhatsAppTemplateTemplatesApiResponse {
	return v.value
}

func (v *NullableWhatsAppTemplateTemplatesApiResponse) Set(val *WhatsAppTemplateTemplatesApiResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppTemplateTemplatesApiResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppTemplateTemplatesApiResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppTemplateTemplatesApiResponse(val *WhatsAppTemplateTemplatesApiResponse) *NullableWhatsAppTemplateTemplatesApiResponse {
	return &NullableWhatsAppTemplateTemplatesApiResponse{value: val, isSet: true}
}

func (v NullableWhatsAppTemplateTemplatesApiResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppTemplateTemplatesApiResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
