/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppApiRequestErrorDetails struct for WhatsAppApiRequestErrorDetails
type WhatsAppApiRequestErrorDetails struct {
	// Identifier of the error.
	MessageId *string `json:"messageId,omitempty"`
	// Detailed error description.
	Text *string `json:"text,omitempty"`
	// Map of validation errors
	ValidationErrors *map[string][]string `json:"validationErrors,omitempty"`
}

// NewWhatsAppApiRequestErrorDetails instantiates a new WhatsAppApiRequestErrorDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppApiRequestErrorDetails() *WhatsAppApiRequestErrorDetails {
	this := WhatsAppApiRequestErrorDetails{}
	return &this
}

// NewWhatsAppApiRequestErrorDetailsWithDefaults instantiates a new WhatsAppApiRequestErrorDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppApiRequestErrorDetailsWithDefaults() *WhatsAppApiRequestErrorDetails {
	this := WhatsAppApiRequestErrorDetails{}
	return &this
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *WhatsAppApiRequestErrorDetails) GetMessageId() string {
	if o == nil || o.MessageId == nil {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppApiRequestErrorDetails) GetMessageIdOk() (*string, bool) {
	if o == nil || o.MessageId == nil {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *WhatsAppApiRequestErrorDetails) HasMessageId() bool {
	if o != nil && o.MessageId != nil {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *WhatsAppApiRequestErrorDetails) SetMessageId(v string) {
	o.MessageId = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *WhatsAppApiRequestErrorDetails) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppApiRequestErrorDetails) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *WhatsAppApiRequestErrorDetails) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *WhatsAppApiRequestErrorDetails) SetText(v string) {
	o.Text = &v
}

// GetValidationErrors returns the ValidationErrors field value if set, zero value otherwise.
func (o *WhatsAppApiRequestErrorDetails) GetValidationErrors() map[string][]string {
	if o == nil || o.ValidationErrors == nil {
		var ret map[string][]string
		return ret
	}
	return *o.ValidationErrors
}

// GetValidationErrorsOk returns a tuple with the ValidationErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppApiRequestErrorDetails) GetValidationErrorsOk() (*map[string][]string, bool) {
	if o == nil || o.ValidationErrors == nil {
		return nil, false
	}
	return o.ValidationErrors, true
}

// HasValidationErrors returns a boolean if a field has been set.
func (o *WhatsAppApiRequestErrorDetails) HasValidationErrors() bool {
	if o != nil && o.ValidationErrors != nil {
		return true
	}

	return false
}

// SetValidationErrors gets a reference to the given map[string][]string and assigns it to the ValidationErrors field.
func (o *WhatsAppApiRequestErrorDetails) SetValidationErrors(v map[string][]string) {
	o.ValidationErrors = &v
}

func (o WhatsAppApiRequestErrorDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MessageId != nil {
		toSerialize["messageId"] = o.MessageId
	}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	if o.ValidationErrors != nil {
		toSerialize["validationErrors"] = o.ValidationErrors
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppApiRequestErrorDetails struct {
	value *WhatsAppApiRequestErrorDetails
	isSet bool
}

func (v NullableWhatsAppApiRequestErrorDetails) Get() *WhatsAppApiRequestErrorDetails {
	return v.value
}

func (v *NullableWhatsAppApiRequestErrorDetails) Set(val *WhatsAppApiRequestErrorDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppApiRequestErrorDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppApiRequestErrorDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppApiRequestErrorDetails(val *WhatsAppApiRequestErrorDetails) *NullableWhatsAppApiRequestErrorDetails {
	return &NullableWhatsAppApiRequestErrorDetails{value: val, isSet: true}
}

func (v NullableWhatsAppApiRequestErrorDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppApiRequestErrorDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
