/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppContactWhatsAppApiContent Array of contacts sent in the WhatsApp message.
type WhatsAppContactWhatsAppApiContent struct {
	// Array of addresses information.
	Addresses *[]WhatsAppAddressWhatsAppApiContent `json:"addresses,omitempty"`
	// Date of birth in `YYYY-MM-DD` format.
	Birthday *string `json:"birthday,omitempty"`
	// Array of emails information.
	Emails *[]WhatsAppEmailWhatsAppApiContent      `json:"emails,omitempty"`
	Name   WhatsAppNameWhatsAppApiContent          `json:"name"`
	Org    *WhatsAppOrganizationWhatsAppApiContent `json:"org,omitempty"`
	// Array of phones information.
	Phones *[]WhatsAppPhoneWhatsAppApiContent `json:"phones,omitempty"`
	// Array of urls information.
	Urls *[]WhatsAppUrlWhatsAppApiContent `json:"urls,omitempty"`
}

// NewWhatsAppContactWhatsAppApiContent instantiates a new WhatsAppContactWhatsAppApiContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppContactWhatsAppApiContent(name WhatsAppNameWhatsAppApiContent) *WhatsAppContactWhatsAppApiContent {
	this := WhatsAppContactWhatsAppApiContent{}
	this.Name = name
	return &this
}

// NewWhatsAppContactWhatsAppApiContentWithDefaults instantiates a new WhatsAppContactWhatsAppApiContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppContactWhatsAppApiContentWithDefaults() *WhatsAppContactWhatsAppApiContent {
	this := WhatsAppContactWhatsAppApiContent{}
	return &this
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *WhatsAppContactWhatsAppApiContent) GetAddresses() []WhatsAppAddressWhatsAppApiContent {
	if o == nil || o.Addresses == nil {
		var ret []WhatsAppAddressWhatsAppApiContent
		return ret
	}
	return *o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppContactWhatsAppApiContent) GetAddressesOk() (*[]WhatsAppAddressWhatsAppApiContent, bool) {
	if o == nil || o.Addresses == nil {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *WhatsAppContactWhatsAppApiContent) HasAddresses() bool {
	if o != nil && o.Addresses != nil {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []WhatsAppAddressWhatsAppApiContent and assigns it to the Addresses field.
func (o *WhatsAppContactWhatsAppApiContent) SetAddresses(v []WhatsAppAddressWhatsAppApiContent) {
	o.Addresses = &v
}

// GetBirthday returns the Birthday field value if set, zero value otherwise.
func (o *WhatsAppContactWhatsAppApiContent) GetBirthday() string {
	if o == nil || o.Birthday == nil {
		var ret string
		return ret
	}
	return *o.Birthday
}

// GetBirthdayOk returns a tuple with the Birthday field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppContactWhatsAppApiContent) GetBirthdayOk() (*string, bool) {
	if o == nil || o.Birthday == nil {
		return nil, false
	}
	return o.Birthday, true
}

// HasBirthday returns a boolean if a field has been set.
func (o *WhatsAppContactWhatsAppApiContent) HasBirthday() bool {
	if o != nil && o.Birthday != nil {
		return true
	}

	return false
}

// SetBirthday gets a reference to the given string and assigns it to the Birthday field.
func (o *WhatsAppContactWhatsAppApiContent) SetBirthday(v string) {
	o.Birthday = &v
}

// GetEmails returns the Emails field value if set, zero value otherwise.
func (o *WhatsAppContactWhatsAppApiContent) GetEmails() []WhatsAppEmailWhatsAppApiContent {
	if o == nil || o.Emails == nil {
		var ret []WhatsAppEmailWhatsAppApiContent
		return ret
	}
	return *o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppContactWhatsAppApiContent) GetEmailsOk() (*[]WhatsAppEmailWhatsAppApiContent, bool) {
	if o == nil || o.Emails == nil {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *WhatsAppContactWhatsAppApiContent) HasEmails() bool {
	if o != nil && o.Emails != nil {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []WhatsAppEmailWhatsAppApiContent and assigns it to the Emails field.
func (o *WhatsAppContactWhatsAppApiContent) SetEmails(v []WhatsAppEmailWhatsAppApiContent) {
	o.Emails = &v
}

// GetName returns the Name field value
func (o *WhatsAppContactWhatsAppApiContent) GetName() WhatsAppNameWhatsAppApiContent {
	if o == nil {
		var ret WhatsAppNameWhatsAppApiContent
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WhatsAppContactWhatsAppApiContent) GetNameOk() (*WhatsAppNameWhatsAppApiContent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WhatsAppContactWhatsAppApiContent) SetName(v WhatsAppNameWhatsAppApiContent) {
	o.Name = v
}

// GetOrg returns the Org field value if set, zero value otherwise.
func (o *WhatsAppContactWhatsAppApiContent) GetOrg() WhatsAppOrganizationWhatsAppApiContent {
	if o == nil || o.Org == nil {
		var ret WhatsAppOrganizationWhatsAppApiContent
		return ret
	}
	return *o.Org
}

// GetOrgOk returns a tuple with the Org field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppContactWhatsAppApiContent) GetOrgOk() (*WhatsAppOrganizationWhatsAppApiContent, bool) {
	if o == nil || o.Org == nil {
		return nil, false
	}
	return o.Org, true
}

// HasOrg returns a boolean if a field has been set.
func (o *WhatsAppContactWhatsAppApiContent) HasOrg() bool {
	if o != nil && o.Org != nil {
		return true
	}

	return false
}

// SetOrg gets a reference to the given WhatsAppOrganizationWhatsAppApiContent and assigns it to the Org field.
func (o *WhatsAppContactWhatsAppApiContent) SetOrg(v WhatsAppOrganizationWhatsAppApiContent) {
	o.Org = &v
}

// GetPhones returns the Phones field value if set, zero value otherwise.
func (o *WhatsAppContactWhatsAppApiContent) GetPhones() []WhatsAppPhoneWhatsAppApiContent {
	if o == nil || o.Phones == nil {
		var ret []WhatsAppPhoneWhatsAppApiContent
		return ret
	}
	return *o.Phones
}

// GetPhonesOk returns a tuple with the Phones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppContactWhatsAppApiContent) GetPhonesOk() (*[]WhatsAppPhoneWhatsAppApiContent, bool) {
	if o == nil || o.Phones == nil {
		return nil, false
	}
	return o.Phones, true
}

// HasPhones returns a boolean if a field has been set.
func (o *WhatsAppContactWhatsAppApiContent) HasPhones() bool {
	if o != nil && o.Phones != nil {
		return true
	}

	return false
}

// SetPhones gets a reference to the given []WhatsAppPhoneWhatsAppApiContent and assigns it to the Phones field.
func (o *WhatsAppContactWhatsAppApiContent) SetPhones(v []WhatsAppPhoneWhatsAppApiContent) {
	o.Phones = &v
}

// GetUrls returns the Urls field value if set, zero value otherwise.
func (o *WhatsAppContactWhatsAppApiContent) GetUrls() []WhatsAppUrlWhatsAppApiContent {
	if o == nil || o.Urls == nil {
		var ret []WhatsAppUrlWhatsAppApiContent
		return ret
	}
	return *o.Urls
}

// GetUrlsOk returns a tuple with the Urls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppContactWhatsAppApiContent) GetUrlsOk() (*[]WhatsAppUrlWhatsAppApiContent, bool) {
	if o == nil || o.Urls == nil {
		return nil, false
	}
	return o.Urls, true
}

// HasUrls returns a boolean if a field has been set.
func (o *WhatsAppContactWhatsAppApiContent) HasUrls() bool {
	if o != nil && o.Urls != nil {
		return true
	}

	return false
}

// SetUrls gets a reference to the given []WhatsAppUrlWhatsAppApiContent and assigns it to the Urls field.
func (o *WhatsAppContactWhatsAppApiContent) SetUrls(v []WhatsAppUrlWhatsAppApiContent) {
	o.Urls = &v
}

func (o WhatsAppContactWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Addresses != nil {
		toSerialize["addresses"] = o.Addresses
	}
	if o.Birthday != nil {
		toSerialize["birthday"] = o.Birthday
	}
	if o.Emails != nil {
		toSerialize["emails"] = o.Emails
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Org != nil {
		toSerialize["org"] = o.Org
	}
	if o.Phones != nil {
		toSerialize["phones"] = o.Phones
	}
	if o.Urls != nil {
		toSerialize["urls"] = o.Urls
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppContactWhatsAppApiContent struct {
	value *WhatsAppContactWhatsAppApiContent
	isSet bool
}

func (v NullableWhatsAppContactWhatsAppApiContent) Get() *WhatsAppContactWhatsAppApiContent {
	return v.value
}

func (v *NullableWhatsAppContactWhatsAppApiContent) Set(val *WhatsAppContactWhatsAppApiContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppContactWhatsAppApiContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppContactWhatsAppApiContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppContactWhatsAppApiContent(val *WhatsAppContactWhatsAppApiContent) *NullableWhatsAppContactWhatsAppApiContent {
	return &NullableWhatsAppContactWhatsAppApiContent{value: val, isSet: true}
}

func (v NullableWhatsAppContactWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppContactWhatsAppApiContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
