/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppTemplateLocationHeaderWhatsAppApiContent struct for WhatsAppTemplateLocationHeaderWhatsAppApiContent
type WhatsAppTemplateLocationHeaderWhatsAppApiContent struct {
	WhatsAppTemplateHeaderWhatsAppApiContent
	// Latitude of a location sent in the header.
	Latitude float64 `json:"latitude"`
	// Longitude of a location sent in the header.
	Longitude float64 `json:"longitude"`
}

// NewWhatsAppTemplateLocationHeaderWhatsAppApiContent instantiates a new WhatsAppTemplateLocationHeaderWhatsAppApiContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppTemplateLocationHeaderWhatsAppApiContent(latitude float64, longitude float64, type_ string) *WhatsAppTemplateLocationHeaderWhatsAppApiContent {
	this := WhatsAppTemplateLocationHeaderWhatsAppApiContent{}
	this.Type = type_
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewWhatsAppTemplateLocationHeaderWhatsAppApiContentWithDefaults instantiates a new WhatsAppTemplateLocationHeaderWhatsAppApiContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppTemplateLocationHeaderWhatsAppApiContentWithDefaults() *WhatsAppTemplateLocationHeaderWhatsAppApiContent {
	this := WhatsAppTemplateLocationHeaderWhatsAppApiContent{}
	return &this
}

// GetLatitude returns the Latitude field value
func (o *WhatsAppTemplateLocationHeaderWhatsAppApiContent) GetLatitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateLocationHeaderWhatsAppApiContent) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *WhatsAppTemplateLocationHeaderWhatsAppApiContent) SetLatitude(v float64) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *WhatsAppTemplateLocationHeaderWhatsAppApiContent) GetLongitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *WhatsAppTemplateLocationHeaderWhatsAppApiContent) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *WhatsAppTemplateLocationHeaderWhatsAppApiContent) SetLongitude(v float64) {
	o.Longitude = v
}

func (o WhatsAppTemplateLocationHeaderWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedWhatsAppTemplateHeaderWhatsAppApiContent, errWhatsAppTemplateHeaderWhatsAppApiContent := json.Marshal(o.WhatsAppTemplateHeaderWhatsAppApiContent)
	if errWhatsAppTemplateHeaderWhatsAppApiContent != nil {
		return []byte{}, errWhatsAppTemplateHeaderWhatsAppApiContent
	}
	errWhatsAppTemplateHeaderWhatsAppApiContent = json.Unmarshal([]byte(serializedWhatsAppTemplateHeaderWhatsAppApiContent), &toSerialize)
	if errWhatsAppTemplateHeaderWhatsAppApiContent != nil {
		return []byte{}, errWhatsAppTemplateHeaderWhatsAppApiContent
	}
	if true {
		toSerialize["latitude"] = o.Latitude
	}
	if true {
		toSerialize["longitude"] = o.Longitude
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent struct {
	value *WhatsAppTemplateLocationHeaderWhatsAppApiContent
	isSet bool
}

func (v NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent) Get() *WhatsAppTemplateLocationHeaderWhatsAppApiContent {
	return v.value
}

func (v *NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent) Set(val *WhatsAppTemplateLocationHeaderWhatsAppApiContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppTemplateLocationHeaderWhatsAppApiContent(val *WhatsAppTemplateLocationHeaderWhatsAppApiContent) *NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent {
	return &NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent{value: val, isSet: true}
}

func (v NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppTemplateLocationHeaderWhatsAppApiContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
