/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// EmailBulkRescheduleResponse struct for EmailBulkRescheduleResponse
type EmailBulkRescheduleResponse struct {
	BulkId *string `json:"bulkId,omitempty"`
	SendAt *Time   `json:"sendAt,omitempty"`
}

// NewEmailBulkRescheduleResponse instantiates a new EmailBulkRescheduleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailBulkRescheduleResponse() *EmailBulkRescheduleResponse {
	this := EmailBulkRescheduleResponse{}
	return &this
}

// NewEmailBulkRescheduleResponseWithDefaults instantiates a new EmailBulkRescheduleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailBulkRescheduleResponseWithDefaults() *EmailBulkRescheduleResponse {
	this := EmailBulkRescheduleResponse{}
	return &this
}

// GetBulkId returns the BulkId field value if set, zero value otherwise.
func (o *EmailBulkRescheduleResponse) GetBulkId() string {
	if o == nil || o.BulkId == nil {
		var ret string
		return ret
	}
	return *o.BulkId
}

// GetBulkIdOk returns a tuple with the BulkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailBulkRescheduleResponse) GetBulkIdOk() (*string, bool) {
	if o == nil || o.BulkId == nil {
		return nil, false
	}
	return o.BulkId, true
}

// HasBulkId returns a boolean if a field has been set.
func (o *EmailBulkRescheduleResponse) HasBulkId() bool {
	if o != nil && o.BulkId != nil {
		return true
	}

	return false
}

// SetBulkId gets a reference to the given string and assigns it to the BulkId field.
func (o *EmailBulkRescheduleResponse) SetBulkId(v string) {
	o.BulkId = &v
}

// GetSendAt returns the SendAt field value if set, zero value otherwise.
func (o *EmailBulkRescheduleResponse) GetSendAt() Time {
	if o == nil || o.SendAt == nil {
		var ret Time
		return ret
	}
	return *o.SendAt
}

// GetSendAtOk returns a tuple with the SendAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailBulkRescheduleResponse) GetSendAtOk() (*Time, bool) {
	if o == nil || o.SendAt == nil {
		return nil, false
	}
	return o.SendAt, true
}

// HasSendAt returns a boolean if a field has been set.
func (o *EmailBulkRescheduleResponse) HasSendAt() bool {
	if o != nil && o.SendAt != nil {
		return true
	}

	return false
}

// SetSendAt gets a reference to the given Time and assigns it to the SendAt field.
func (o *EmailBulkRescheduleResponse) SetSendAt(v Time) {
	o.SendAt = &v
}

func (o EmailBulkRescheduleResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BulkId != nil {
		toSerialize["bulkId"] = o.BulkId
	}
	if o.SendAt != nil {
		toSerialize["sendAt"] = o.SendAt
	}
	return json.Marshal(toSerialize)
}

type NullableEmailBulkRescheduleResponse struct {
	value *EmailBulkRescheduleResponse
	isSet bool
}

func (v NullableEmailBulkRescheduleResponse) Get() *EmailBulkRescheduleResponse {
	return v.value
}

func (v *NullableEmailBulkRescheduleResponse) Set(val *EmailBulkRescheduleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailBulkRescheduleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailBulkRescheduleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailBulkRescheduleResponse(val *EmailBulkRescheduleResponse) *NullableEmailBulkRescheduleResponse {
	return &NullableEmailBulkRescheduleResponse{value: val, isSet: true}
}

func (v NullableEmailBulkRescheduleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailBulkRescheduleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
