/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// EmailReport struct for EmailReport
type EmailReport struct {
	BulkId       *string      `json:"bulkId,omitempty"`
	DoneAt       *Time        `json:"doneAt,omitempty"`
	Error        *EmailError  `json:"error,omitempty"`
	MccMnc       *string      `json:"mccMnc,omitempty"`
	MessageCount *int32       `json:"messageCount,omitempty"`
	MessageId    *string      `json:"messageId,omitempty"`
	Price        *EmailPrice  `json:"price,omitempty"`
	SentAt       *Time        `json:"sentAt,omitempty"`
	Status       *EmailStatus `json:"status,omitempty"`
	To           *string      `json:"to,omitempty"`
}

// NewEmailReport instantiates a new EmailReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailReport() *EmailReport {
	this := EmailReport{}
	return &this
}

// NewEmailReportWithDefaults instantiates a new EmailReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailReportWithDefaults() *EmailReport {
	this := EmailReport{}
	return &this
}

// GetBulkId returns the BulkId field value if set, zero value otherwise.
func (o *EmailReport) GetBulkId() string {
	if o == nil || o.BulkId == nil {
		var ret string
		return ret
	}
	return *o.BulkId
}

// GetBulkIdOk returns a tuple with the BulkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetBulkIdOk() (*string, bool) {
	if o == nil || o.BulkId == nil {
		return nil, false
	}
	return o.BulkId, true
}

// HasBulkId returns a boolean if a field has been set.
func (o *EmailReport) HasBulkId() bool {
	if o != nil && o.BulkId != nil {
		return true
	}

	return false
}

// SetBulkId gets a reference to the given string and assigns it to the BulkId field.
func (o *EmailReport) SetBulkId(v string) {
	o.BulkId = &v
}

// GetDoneAt returns the DoneAt field value if set, zero value otherwise.
func (o *EmailReport) GetDoneAt() Time {
	if o == nil || o.DoneAt == nil {
		var ret Time
		return ret
	}
	return *o.DoneAt
}

// GetDoneAtOk returns a tuple with the DoneAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetDoneAtOk() (*Time, bool) {
	if o == nil || o.DoneAt == nil {
		return nil, false
	}
	return o.DoneAt, true
}

// HasDoneAt returns a boolean if a field has been set.
func (o *EmailReport) HasDoneAt() bool {
	if o != nil && o.DoneAt != nil {
		return true
	}

	return false
}

// SetDoneAt gets a reference to the given Time and assigns it to the DoneAt field.
func (o *EmailReport) SetDoneAt(v Time) {
	o.DoneAt = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *EmailReport) GetError() EmailError {
	if o == nil || o.Error == nil {
		var ret EmailError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetErrorOk() (*EmailError, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *EmailReport) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given EmailError and assigns it to the Error field.
func (o *EmailReport) SetError(v EmailError) {
	o.Error = &v
}

// GetMccMnc returns the MccMnc field value if set, zero value otherwise.
func (o *EmailReport) GetMccMnc() string {
	if o == nil || o.MccMnc == nil {
		var ret string
		return ret
	}
	return *o.MccMnc
}

// GetMccMncOk returns a tuple with the MccMnc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetMccMncOk() (*string, bool) {
	if o == nil || o.MccMnc == nil {
		return nil, false
	}
	return o.MccMnc, true
}

// HasMccMnc returns a boolean if a field has been set.
func (o *EmailReport) HasMccMnc() bool {
	if o != nil && o.MccMnc != nil {
		return true
	}

	return false
}

// SetMccMnc gets a reference to the given string and assigns it to the MccMnc field.
func (o *EmailReport) SetMccMnc(v string) {
	o.MccMnc = &v
}

// GetMessageCount returns the MessageCount field value if set, zero value otherwise.
func (o *EmailReport) GetMessageCount() int32 {
	if o == nil || o.MessageCount == nil {
		var ret int32
		return ret
	}
	return *o.MessageCount
}

// GetMessageCountOk returns a tuple with the MessageCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetMessageCountOk() (*int32, bool) {
	if o == nil || o.MessageCount == nil {
		return nil, false
	}
	return o.MessageCount, true
}

// HasMessageCount returns a boolean if a field has been set.
func (o *EmailReport) HasMessageCount() bool {
	if o != nil && o.MessageCount != nil {
		return true
	}

	return false
}

// SetMessageCount gets a reference to the given int32 and assigns it to the MessageCount field.
func (o *EmailReport) SetMessageCount(v int32) {
	o.MessageCount = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *EmailReport) GetMessageId() string {
	if o == nil || o.MessageId == nil {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetMessageIdOk() (*string, bool) {
	if o == nil || o.MessageId == nil {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *EmailReport) HasMessageId() bool {
	if o != nil && o.MessageId != nil {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *EmailReport) SetMessageId(v string) {
	o.MessageId = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *EmailReport) GetPrice() EmailPrice {
	if o == nil || o.Price == nil {
		var ret EmailPrice
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetPriceOk() (*EmailPrice, bool) {
	if o == nil || o.Price == nil {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *EmailReport) HasPrice() bool {
	if o != nil && o.Price != nil {
		return true
	}

	return false
}

// SetPrice gets a reference to the given EmailPrice and assigns it to the Price field.
func (o *EmailReport) SetPrice(v EmailPrice) {
	o.Price = &v
}

// GetSentAt returns the SentAt field value if set, zero value otherwise.
func (o *EmailReport) GetSentAt() Time {
	if o == nil || o.SentAt == nil {
		var ret Time
		return ret
	}
	return *o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetSentAtOk() (*Time, bool) {
	if o == nil || o.SentAt == nil {
		return nil, false
	}
	return o.SentAt, true
}

// HasSentAt returns a boolean if a field has been set.
func (o *EmailReport) HasSentAt() bool {
	if o != nil && o.SentAt != nil {
		return true
	}

	return false
}

// SetSentAt gets a reference to the given Time and assigns it to the SentAt field.
func (o *EmailReport) SetSentAt(v Time) {
	o.SentAt = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailReport) GetStatus() EmailStatus {
	if o == nil || o.Status == nil {
		var ret EmailStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetStatusOk() (*EmailStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailReport) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given EmailStatus and assigns it to the Status field.
func (o *EmailReport) SetStatus(v EmailStatus) {
	o.Status = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *EmailReport) GetTo() string {
	if o == nil || o.To == nil {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailReport) GetToOk() (*string, bool) {
	if o == nil || o.To == nil {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *EmailReport) HasTo() bool {
	if o != nil && o.To != nil {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *EmailReport) SetTo(v string) {
	o.To = &v
}

func (o EmailReport) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BulkId != nil {
		toSerialize["bulkId"] = o.BulkId
	}
	if o.DoneAt != nil {
		toSerialize["doneAt"] = o.DoneAt
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	if o.MccMnc != nil {
		toSerialize["mccMnc"] = o.MccMnc
	}
	if o.MessageCount != nil {
		toSerialize["messageCount"] = o.MessageCount
	}
	if o.MessageId != nil {
		toSerialize["messageId"] = o.MessageId
	}
	if o.Price != nil {
		toSerialize["price"] = o.Price
	}
	if o.SentAt != nil {
		toSerialize["sentAt"] = o.SentAt
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.To != nil {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullableEmailReport struct {
	value *EmailReport
	isSet bool
}

func (v NullableEmailReport) Get() *EmailReport {
	return v.value
}

func (v *NullableEmailReport) Set(val *EmailReport) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailReport) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailReport(val *EmailReport) *NullableEmailReport {
	return &NullableEmailReport{value: val, isSet: true}
}

func (v NullableEmailReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
