/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// WhatsAppDocumentWhatsAppApiContent Content of the message that will be sent.
type WhatsAppDocumentWhatsAppApiContent struct {
	// URL of a document sent in the WhatsApp message. It is expected to be a valid URL starting with `https://`, `http://` or `ftp://`. Maximum document size is 100MB.
	MediaUrl string `json:"mediaUrl"`
	// Caption of the document.
	Caption *string `json:"caption,omitempty"`
	// Filename of the document.
	Filename *string `json:"filename,omitempty"`
}

// NewWhatsAppDocumentWhatsAppApiContent instantiates a new WhatsAppDocumentWhatsAppApiContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppDocumentWhatsAppApiContent(mediaUrl string) *WhatsAppDocumentWhatsAppApiContent {
	this := WhatsAppDocumentWhatsAppApiContent{}
	this.MediaUrl = mediaUrl
	return &this
}

// NewWhatsAppDocumentWhatsAppApiContentWithDefaults instantiates a new WhatsAppDocumentWhatsAppApiContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppDocumentWhatsAppApiContentWithDefaults() *WhatsAppDocumentWhatsAppApiContent {
	this := WhatsAppDocumentWhatsAppApiContent{}
	return &this
}

// GetMediaUrl returns the MediaUrl field value
func (o *WhatsAppDocumentWhatsAppApiContent) GetMediaUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MediaUrl
}

// GetMediaUrlOk returns a tuple with the MediaUrl field value
// and a boolean to check if the value has been set.
func (o *WhatsAppDocumentWhatsAppApiContent) GetMediaUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MediaUrl, true
}

// SetMediaUrl sets field value
func (o *WhatsAppDocumentWhatsAppApiContent) SetMediaUrl(v string) {
	o.MediaUrl = v
}

// GetCaption returns the Caption field value if set, zero value otherwise.
func (o *WhatsAppDocumentWhatsAppApiContent) GetCaption() string {
	if o == nil || o.Caption == nil {
		var ret string
		return ret
	}
	return *o.Caption
}

// GetCaptionOk returns a tuple with the Caption field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppDocumentWhatsAppApiContent) GetCaptionOk() (*string, bool) {
	if o == nil || o.Caption == nil {
		return nil, false
	}
	return o.Caption, true
}

// HasCaption returns a boolean if a field has been set.
func (o *WhatsAppDocumentWhatsAppApiContent) HasCaption() bool {
	if o != nil && o.Caption != nil {
		return true
	}

	return false
}

// SetCaption gets a reference to the given string and assigns it to the Caption field.
func (o *WhatsAppDocumentWhatsAppApiContent) SetCaption(v string) {
	o.Caption = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *WhatsAppDocumentWhatsAppApiContent) GetFilename() string {
	if o == nil || o.Filename == nil {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppDocumentWhatsAppApiContent) GetFilenameOk() (*string, bool) {
	if o == nil || o.Filename == nil {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *WhatsAppDocumentWhatsAppApiContent) HasFilename() bool {
	if o != nil && o.Filename != nil {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *WhatsAppDocumentWhatsAppApiContent) SetFilename(v string) {
	o.Filename = &v
}

func (o WhatsAppDocumentWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mediaUrl"] = o.MediaUrl
	}
	if o.Caption != nil {
		toSerialize["caption"] = o.Caption
	}
	if o.Filename != nil {
		toSerialize["filename"] = o.Filename
	}
	return json.Marshal(toSerialize)
}

type NullableWhatsAppDocumentWhatsAppApiContent struct {
	value *WhatsAppDocumentWhatsAppApiContent
	isSet bool
}

func (v NullableWhatsAppDocumentWhatsAppApiContent) Get() *WhatsAppDocumentWhatsAppApiContent {
	return v.value
}

func (v *NullableWhatsAppDocumentWhatsAppApiContent) Set(val *WhatsAppDocumentWhatsAppApiContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppDocumentWhatsAppApiContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppDocumentWhatsAppApiContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppDocumentWhatsAppApiContent(val *WhatsAppDocumentWhatsAppApiContent) *NullableWhatsAppDocumentWhatsAppApiContent {
	return &NullableWhatsAppDocumentWhatsAppApiContent{value: val, isSet: true}
}

func (v NullableWhatsAppDocumentWhatsAppApiContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppDocumentWhatsAppApiContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
