/**
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * Contact: support@infobip.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */

package infobip

import (
	"encoding/json"
)

// EmailBulkStatusInfo struct for EmailBulkStatusInfo
type EmailBulkStatusInfo struct {
	BulkId *string          `json:"bulkId,omitempty"`
	Status *EmailBulkStatus `json:"status,omitempty"`
}

// NewEmailBulkStatusInfo instantiates a new EmailBulkStatusInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailBulkStatusInfo() *EmailBulkStatusInfo {
	this := EmailBulkStatusInfo{}
	return &this
}

// NewEmailBulkStatusInfoWithDefaults instantiates a new EmailBulkStatusInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailBulkStatusInfoWithDefaults() *EmailBulkStatusInfo {
	this := EmailBulkStatusInfo{}
	return &this
}

// GetBulkId returns the BulkId field value if set, zero value otherwise.
func (o *EmailBulkStatusInfo) GetBulkId() string {
	if o == nil || o.BulkId == nil {
		var ret string
		return ret
	}
	return *o.BulkId
}

// GetBulkIdOk returns a tuple with the BulkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailBulkStatusInfo) GetBulkIdOk() (*string, bool) {
	if o == nil || o.BulkId == nil {
		return nil, false
	}
	return o.BulkId, true
}

// HasBulkId returns a boolean if a field has been set.
func (o *EmailBulkStatusInfo) HasBulkId() bool {
	if o != nil && o.BulkId != nil {
		return true
	}

	return false
}

// SetBulkId gets a reference to the given string and assigns it to the BulkId field.
func (o *EmailBulkStatusInfo) SetBulkId(v string) {
	o.BulkId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EmailBulkStatusInfo) GetStatus() EmailBulkStatus {
	if o == nil || o.Status == nil {
		var ret EmailBulkStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailBulkStatusInfo) GetStatusOk() (*EmailBulkStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EmailBulkStatusInfo) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given EmailBulkStatus and assigns it to the Status field.
func (o *EmailBulkStatusInfo) SetStatus(v EmailBulkStatus) {
	o.Status = &v
}

func (o EmailBulkStatusInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BulkId != nil {
		toSerialize["bulkId"] = o.BulkId
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableEmailBulkStatusInfo struct {
	value *EmailBulkStatusInfo
	isSet bool
}

func (v NullableEmailBulkStatusInfo) Get() *EmailBulkStatusInfo {
	return v.value
}

func (v *NullableEmailBulkStatusInfo) Set(val *EmailBulkStatusInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailBulkStatusInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailBulkStatusInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailBulkStatusInfo(val *EmailBulkStatusInfo) *NullableEmailBulkStatusInfo {
	return &NullableEmailBulkStatusInfo{value: val, isSet: true}
}

func (v NullableEmailBulkStatusInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailBulkStatusInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
